// Copyright 2026 IOTA Stiftung.
// SPDX-License-Identifier: Apache-2.0.
// This file is generated by ts-to-schema, do not edit it directly.
// @ts-nocheck
/* cspell:disable */
import type { ICompiledValidator } from "@twin.org/data-core";
import * as external0 from "@twin.org/standards-w3c-did";
import * as external1 from "../models/immutableProofFailure.js";
const MESSAGES = ["must NOT have more than 2 items","must NOT have fewer than 2 items","must be equal to constant","must be array","must be string","must be object","must be boolean"];
function createError(instancePath, schemaPath, keyword, params, message) {
return { instancePath, schemaPath, keyword, params, ["message"]: typeof message === "number" ? MESSAGES[message] : message };
}
function pushError(errors, error) {
if (errors === null) {
return [error];
}
errors.push(error);
return errors;
}
/**
 * Compiled validator for the ImmutableProof schema.
 */
export const CompiledImmutableProof: ICompiledValidator = validate52;

function validate52(data, {instancePath="", parentData, parentDataProperty, rootData=data, dynamicAnchors={}}={}){
/*# sourceURL="https://schema.twindev.org/immutable-proof/ImmutableProof" */;
let vErrors = null;
let errors = 0;
const evaluated0 = validate52.evaluated;
if(evaluated0.dynamicProps){
evaluated0.props = undefined;
}
if(evaluated0.dynamicItems){
evaluated0.items = undefined;
}
if(data && typeof data == "object" && !Array.isArray(data)){
if(data.proofIntegrity === undefined){
const err0 = createError(instancePath,"#/required","required",{missingProperty: "proofIntegrity"},"must have required property '"+"proofIntegrity"+"'");
vErrors = pushError(vErrors, err0);
errors++;
}
if(data["@context"] !== undefined){
let data0 = data["@context"];
if(Array.isArray(data0)){
if(data0.length > 2){
const err1 = createError(instancePath+"/@context","#/properties/%40context/maxItems","maxItems",{limit: 2},0);
vErrors = pushError(vErrors, err1);
errors++;
}
if(data0.length < 2){
const err2 = createError(instancePath+"/@context","#/properties/%40context/minItems","minItems",{limit: 2},1);
vErrors = pushError(vErrors, err2);
errors++;
}
const len0 = data0.length;
if(len0 > 0){
if("https://schema.twindev.org/immutable-proof/" !== data0[0]){
const err3 = createError(instancePath+"/@context/0","#/properties/%40context/prefixItems/0/const","const",{allowedValue: "https://schema.twindev.org/immutable-proof/"},2);
vErrors = pushError(vErrors, err3);
errors++;
}
}
if(len0 > 1){
if("https://schema.twindev.org/common/" !== data0[1]){
const err4 = createError(instancePath+"/@context/1","#/properties/%40context/prefixItems/1/const","const",{allowedValue: "https://schema.twindev.org/common/"},2);
vErrors = pushError(vErrors, err4);
errors++;
}
}
const len1 = data0.length;
if(!(len1 <= 2)){
const err5 = createError(instancePath+"/@context","#/properties/%40context/items","items",{limit: 2},0);
vErrors = pushError(vErrors, err5);
errors++;
}
}
else {
const err6 = createError(instancePath+"/@context","#/properties/%40context/type","type",{type: "array"},3);
vErrors = pushError(vErrors, err6);
errors++;
}
}
if(data.type !== undefined){
if("ImmutableProof" !== data.type){
const err7 = createError(instancePath+"/type","#/properties/type/const","const",{allowedValue: "ImmutableProof"},2);
vErrors = pushError(vErrors, err7);
errors++;
}
}
if(data.id !== undefined){
if(typeof data.id !== "string"){
const err8 = createError(instancePath+"/id","#/properties/id/type","type",{type: "string"},4);
vErrors = pushError(vErrors, err8);
errors++;
}
}
if(data.proofIntegrity !== undefined){
if(typeof data.proofIntegrity !== "string"){
const err9 = createError(instancePath+"/proofIntegrity","#/properties/proofIntegrity/type","type",{type: "string"},4);
vErrors = pushError(vErrors, err9);
errors++;
}
}
}
else {
const err10 = createError(instancePath,"#/type","type",{type: "object"},5);
vErrors = pushError(vErrors, err10);
errors++;
}
validate52.errors = vErrors;
return errors === 0;
}
validate52.evaluated = {"props":{"@context":true,"type":true,"id":true,"proofIntegrity":true},"dynamicProps":false,"dynamicItems":false};

/**
 * Compiled validator for the ImmutableProofCredential schema.
 */
export const CompiledImmutableProofCredential: ICompiledValidator = validate53;
const keyword0 = external0["CompiledDidVerifiableCredential"];
const keyword1 = external0["CompiledProof"];

function validate54(data, {instancePath="", parentData, parentDataProperty, rootData=data, dynamicAnchors={}}={}){
/*# sourceURL="https://schema.twindev.org/immutable-proof/ImmutableProofDataIntegrity" */;
let vErrors = null;
let errors = 0;
const evaluated0 = validate54.evaluated;
if(evaluated0.dynamicProps){
evaluated0.props = undefined;
}
if(evaluated0.dynamicItems){
evaluated0.items = undefined;
}
if(data && typeof data == "object" && !Array.isArray(data)){
if(data.notarizationId !== undefined){
if(typeof data.notarizationId !== "string"){
const err0 = createError(instancePath+"/notarizationId","#/properties/notarizationId/type","type",{type: "string"},4);
vErrors = pushError(vErrors, err0);
errors++;
}
}
}
else {
const err1 = createError(instancePath,"#/type","type",{type: "object"},5);
vErrors = pushError(vErrors, err1);
errors++;
}
validate54.errors = vErrors;
return errors === 0;
}
validate54.evaluated = {"props":{"notarizationId":true},"dynamicProps":false,"dynamicItems":false};


function validate53(data, {instancePath="", parentData, parentDataProperty, rootData=data, dynamicAnchors={}}={}){
/*# sourceURL="https://schema.twindev.org/immutable-proof/ImmutableProofCredential" */;
let vErrors = null;
let errors = 0;
const evaluated0 = validate53.evaluated;
if(evaluated0.dynamicProps){
evaluated0.props = undefined;
}
if(evaluated0.dynamicItems){
evaluated0.items = undefined;
}
if(!(keyword0(data, {instancePath,parentData,parentDataProperty,rootData,dynamicAnchors}))){
vErrors = vErrors === null ? keyword0.errors : vErrors.concat(keyword0.errors);
errors = vErrors.length;
}
else {
var props0 = keyword0.evaluated.props;
}
if(data && typeof data == "object" && !Array.isArray(data)){
if(props0 !== true){
props0 = props0 || {};
props0.proof = true;
}
if(data.proof !== undefined){
let data0 = data.proof;
if(!(keyword1(data0, {instancePath:instancePath+"/proof",parentData:data,parentDataProperty:"proof",rootData,dynamicAnchors}))){
vErrors = vErrors === null ? keyword1.errors : vErrors.concat(keyword1.errors);
errors = vErrors.length;
}
else {
var props1 = keyword1.evaluated.props;
}
if(!(validate54(data0, {instancePath:instancePath+"/proof",parentData:data,parentDataProperty:"proof",rootData,dynamicAnchors}))){
vErrors = vErrors === null ? validate54.errors : vErrors.concat(validate54.errors);
errors = vErrors.length;
}
if(props1 !== true){
props1 = props1 || {};
props1.notarizationId = true;
}
}
}
else {
const err0 = createError(instancePath,"#/type","type",{type: "object"},5);
vErrors = pushError(vErrors, err0);
errors++;
}
validate53.errors = vErrors;
evaluated0.props = props0;
return errors === 0;
}
validate53.evaluated = {"dynamicProps":true,"dynamicItems":false};

/**
 * Compiled validator for the ImmutableProofDataIntegrity schema.
 */
export const CompiledImmutableProofDataIntegrity: ICompiledValidator = validate54;

/**
 * Compiled validator for the ImmutableProofVerification schema.
 */
export const CompiledImmutableProofVerification: ICompiledValidator = validate56;
const keyword2 = Object.values(external1["ImmutableProofFailure"]);

function validate57(data, {instancePath="", parentData, parentDataProperty, rootData=data, dynamicAnchors={}}={}){
/*# sourceURL="https://schema.twindev.org/immutable-proof/ImmutableProofFailure" */;
let vErrors = null;
let errors = 0;
const evaluated0 = validate57.evaluated;
if(evaluated0.dynamicProps){
evaluated0.props = undefined;
}
if(evaluated0.dynamicItems){
evaluated0.items = undefined;
}
if(!keyword2.includes(data)){
for(let i0 = 0; i0 < keyword2.length; i0++){
vErrors = pushError(vErrors, createError(instancePath, "#/anyOf" + "/" + i0 + "/const", "const", { allowedValue: keyword2[i0] }, "must be equal to constant"));
errors++;
}
vErrors = pushError(vErrors, createError(instancePath, "#/anyOf", "anyOf", {}, "must match a schema in anyOf"));
errors++;
}
validate57.errors = vErrors;
return errors === 0;
}
validate57.evaluated = {"dynamicProps":false,"dynamicItems":false};


function validate56(data, {instancePath="", parentData, parentDataProperty, rootData=data, dynamicAnchors={}}={}){
/*# sourceURL="https://schema.twindev.org/immutable-proof/ImmutableProofVerification" */;
let vErrors = null;
let errors = 0;
const evaluated0 = validate56.evaluated;
if(evaluated0.dynamicProps){
evaluated0.props = undefined;
}
if(evaluated0.dynamicItems){
evaluated0.items = undefined;
}
if(data && typeof data == "object" && !Array.isArray(data)){
if(data["@context"] === undefined){
const err0 = createError(instancePath,"#/required","required",{missingProperty: "@context"},"must have required property '"+"@context"+"'");
vErrors = pushError(vErrors, err0);
errors++;
}
if(data.type === undefined){
const err1 = createError(instancePath,"#/required","required",{missingProperty: "type"},"must have required property '"+"type"+"'");
vErrors = pushError(vErrors, err1);
errors++;
}
if(data.verified === undefined){
const err2 = createError(instancePath,"#/required","required",{missingProperty: "verified"},"must have required property '"+"verified"+"'");
vErrors = pushError(vErrors, err2);
errors++;
}
if(data["@context"] !== undefined){
if("https://schema.twindev.org/immutable-proof/" !== data["@context"]){
const err3 = createError(instancePath+"/@context","#/properties/%40context/const","const",{allowedValue: "https://schema.twindev.org/immutable-proof/"},2);
vErrors = pushError(vErrors, err3);
errors++;
}
}
if(data.type !== undefined){
if("ImmutableProofVerification" !== data.type){
const err4 = createError(instancePath+"/type","#/properties/type/const","const",{allowedValue: "ImmutableProofVerification"},2);
vErrors = pushError(vErrors, err4);
errors++;
}
}
if(data.verified !== undefined){
if(typeof data.verified !== "boolean"){
const err5 = createError(instancePath+"/verified","#/properties/verified/type","type",{type: "boolean"},6);
vErrors = pushError(vErrors, err5);
errors++;
}
}
if(data.failure !== undefined){
if(!(validate57(data.failure, {instancePath:instancePath+"/failure",parentData:data,parentDataProperty:"failure",rootData,dynamicAnchors}))){
vErrors = vErrors === null ? validate57.errors : vErrors.concat(validate57.errors);
errors = vErrors.length;
}
}
}
else {
const err6 = createError(instancePath,"#/type","type",{type: "object"},5);
vErrors = pushError(vErrors, err6);
errors++;
}
validate56.errors = vErrors;
return errors === 0;
}
validate56.evaluated = {"props":{"@context":true,"type":true,"verified":true,"failure":true},"dynamicProps":false,"dynamicItems":false};

/**
 * Compiled validator for the ImmutableProofFailure schema.
 */
export const CompiledImmutableProofFailure: ICompiledValidator = validate57;

